### ISSUE TITLE
Integrate recent MyMonero updates (including RingCT)

### ISSUE THREAD

**Issue by dternyak** [JamesCullum/Safer-MyMonero#2]

**Comment by JamesCullum** [comment]
Is MyMonero working now and will be like this for some time?
And can you assist with it?

**Comment by dternyak** [comment]
MyMonero does indeed have RingCT integrated into their production system.

What help do you need exactly? If you were able to compile this repository you should be able to complete this update as well.

**Comment by JamesCullum** [comment]
No, I mean do you know if they finished their work on it? Otherwise I'd need to update it again quite soon. And of course I am able to do it, but the question was whether you could help with it from an effort perspective.

**Comment by dternyak** [comment]
Yes, they have finished [their work](https://www.reddit.com/r/Monero/comments/5tfz27/why_not_use_opensourced_mymonero_fronend_as_quick/ddmd6bm/?st=iz334r3b&sh=234996fa)

I can certainly help if you would like, but I don't know what specific files have changed. Maybe /u/endogenic on reddit can help point us in the right direction.

**Comment by JamesCullum** [comment]
Same applies to me and basically the JS files just need to be updated with the safeguard copy-pasted into it again - so far, the update is very easy to do but a hassle, hence the question :P 

Do you want to ask him/asked him already or shall I?

**Comment by dternyak** [comment]
@JamesCullum Wow - great job.

**Comment by JamesCullum** [comment]
All I did is dump the files and apply the few fixes, no big deal :) I removed the safeguard now due to the CSP settings - the safeguard is supposed to protect against XSS, but thats not possible anyways.
